# Generated by Django 3.0.5 on 2021-02-03 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=10, verbose_name='API KEY ID')),
                ('create_time', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='創建時間')),
                ('ip', models.CharField(max_length=100, verbose_name='IP來源')),
            ],
            options={
                'verbose_name': 'API LOG',
                'verbose_name_plural': 'API LOG',
                'managed': True,
            },
        ),
    ]
