# Generated by Django 3.0.5 on 2021-02-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='user_id',
            field=models.IntegerField(max_length=2, verbose_name='API KEY ID'),
        ),
    ]
