# Generated by Django 3.1.4 on 2021-01-22 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemInfo',
        ),
    ]
