# Generated by Django 3.1.4 on 2021-01-22 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0002_delete_systeminfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='專題名稱')),
                ('code', models.CharField(max_length=100, verbose_name='專題代號_英文')),
                ('text', models.CharField(max_length=200, verbose_name='專題簡介')),
                ('create_time', models.DateTimeField(verbose_name='創建時間')),
            ],
            options={
                'verbose_name': '專題名稱',
                'verbose_name_plural': '專題名稱s',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='中文')),
                ('name_eng', models.CharField(max_length=100, verbose_name='英文')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.project')),
            ],
            options={
                'verbose_name': '專案系統介面資訊',
                'verbose_name_plural': '專案系統介面資訊s',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
