# Generated by Django 3.1.4 on 2021-01-26 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20210126_1434'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
    ]
