# Generated by Django 3.1.6 on 2021-02-05 14:05

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_delete_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='system/banner/2021/02', verbose_name='視覺圖'),
        ),
    ]
