# Generated by Django 3.1.4 on 2021-01-22 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='文章標題')),
                ('subtitle', models.CharField(max_length=100, verbose_name='文章次標')),
                ('content', models.TextField()),
                ('create_time', models.DateField()),
                ('flag', models.CharField(max_length=10, verbose_name='專題flag')),
            ],
            options={
                'verbose_name': '文章列表',
                'verbose_name_plural': '文章列表',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ArticleCategoryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.articleinfo')),
            ],
            options={
                'verbose_name': '文章分類',
                'verbose_name_plural': '文章分類',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
