# Generated by Django 3.1.4 on 2021-01-22 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_message_project'),
        ('article', '0002_auto_20210122_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='create_date',
            new_name='create_time',
        ),
        migrations.AddField(
            model_name='info',
            name='sort',
            field=models.IntegerField(blank=True, null=True, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='info',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.project', verbose_name='專案名稱'),
        ),
        migrations.AlterField(
            model_name='info',
            name='flag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.project', verbose_name='專題分類'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
