# Generated by Django 3.1.4 on 2021-01-26 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20210122_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='create_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='創建時間'),
        ),
        migrations.AlterField(
            model_name='info',
            name='status',
            field=models.BooleanField(default=False, verbose_name='文章上下架'),
        ),
    ]
