# Generated by Django 3.1.4 on 2021-01-26 15:01

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20210126_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', stdimage.models.StdImageField(blank=True, null=True, upload_to='system/photo/2021/01', verbose_name='PHOTO')),
                ('text', models.CharField(max_length=200, verbose_name='圖說')),
                ('article', models.ManyToManyField(to='article.Info')),
            ],
            options={
                'verbose_name': '相本圖庫',
                'verbose_name_plural': '相本圖庫s',
                'managed': True,
            },
        ),
    ]
