# Generated by Django 3.1.4 on 2021-01-26 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='article',
        ),
    ]
