# Generated by Django 3.1.4 on 2021-01-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_remove_album_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='article',
            field=models.ManyToManyField(to='article.Info', verbose_name='相關文章'),
        ),
    ]
