# Generated by Django 3.1.4 on 2021-01-26 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_album_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='article',
        ),
    ]
