# Generated by Django 3.1.4 on 2021-01-26 17:04

import DjangoUeditor.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_album_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='system/photo/2021/01', verbose_name='視覺圖'),
        ),
        migrations.AlterField(
            model_name='info',
            name='content',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='内容详情'),
        ),
    ]
