# Generated by Django 3.1.4 on 2021-01-26 17:05

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20210126_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='content_rich',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='内容详情'),
        ),
        migrations.AlterField(
            model_name='info',
            name='content',
            field=models.TextField(verbose_name='內文'),
        ),
    ]
