# Generated by Django 3.1.4 on 2021-01-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20210126_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='作者名稱')),
                ('sex', models.CharField(choices=[('male', '男性'), ('female', '女性')], default='male', max_length=10)),
            ],
        ),
    ]
