# Generated by Django 3.1.4 on 2021-01-28 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'managed': True, 'verbose_name': '作者資料', 'verbose_name_plural': '作者資料s'},
        ),
        migrations.RemoveField(
            model_name='author',
            name='sex',
        ),
        migrations.AlterModelTable(
            name='author',
            table='',
        ),
    ]
