# Generated by Django 3.1.6 on 2021-02-05 14:05

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_auto_20210128_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='system/photo/2021/02', verbose_name='視覺圖'),
        ),
    ]
